# 全局配置
mixed-port: 7890 # HTTP(S) 和 SOCKS 代理混合端口
redir-port: 7891 # 透明代理端口，用于 Linux 和 MacOS
tproxy-port: 7892 # 透明代理端口，用于 Linux (TProxy TCP and TProxy UDP)
# port: 7893 # HTTP(S) 代理服务器端口
# socks-port: 7894 # SOCKS5 代理端口
allow-lan: true # 允许局域网连接
bind-address: '*' # 绑定 IP 地址，仅作用于 allow-lan 为 true 时，'*'表示所有地址
skip-auth-prefixes: # 设置跳过验证的 IP 段
  - 127.0.0.1/8
  - ::1/128
lan-allowed-ips: # 允许连接的 IP 地址段，仅作用于 allow-lan 为 true, 默认值为 0.0.0.0/0 和::/0
  - 0.0.0.0/0
  - ::/0
mode: rule # 'rule' 规则 / 'global' 全局 / 'direct' 直连
log-level: warning # 日志等级 silent/error/warning/info/debug
ipv6: false # IPv6 总开关，关闭阻断所有 IPv6 链接和屏蔽 DNS 请求 AAAA 记录
keep-alive-interval: 1800 #TCP Keep Alive 包的间隔，单位为秒
keep-alive-idle: 60 # TCP Keep Alive 的最大空闲时间
disable-keep-alive: false # 禁用 TCP Keep Alive

# 缓存
profile:
  store-selected: true # 存储 select 选择记录
  store-fake-ip: true # 持久化 fake-ip

unified-delay: true # 统一延迟，更换延迟计算方式，通过去除握手等额外开销来降低延迟数值
tcp-concurrent: false # TCP 并发，TCP 并发请求所有 IP 地址，然后选择延迟最低的一个进行连接

# 全局 TLS 指纹，优先低于 proxy 内的 client-fingerprint
# 可选： "chrome","firefox","safari","ios","random","none" options.
global-client-fingerprint: chrome

# GEOIP 数据模式
geodata-mode: false # 更改 geoip 使用文件，mmdb 或者 dat，可选 true/false，true为dat，此项有默认值 false
geodata-loader: memconservative # GEO 文件加载模式
geo-auto-update: true # 是否自动更新 GEO
geo-update-interval: 720 # 更新间隔，单位：小时
# 自定义 GEO 下载地址
geox-url:
  geoip: "https://gitee.com/hoofei/clash/raw/main/data/geoip.dat"
  geosite: "https://gitee.com/hoofei/clash/raw/main/data/geosite.dat"
  mmdb: "https://gitee.com/hoofei/clash/raw/main/data/country.mmdb"
  asn: "https://gitee.com/hoofei/clash/raw/main/data/GeoLite2-ASN.mmdb"

global-ua: clash.meta # 自定义外部资源下载时使用的的 UA

# TUN 配置
tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true
  strict-route: true

# DNS 配置
dns:
  enable: true # 关闭将使用系统 DNS
  prefer-h3: false # 是否开启 DoH 支持 HTTP/3，将并发尝试
  listen: 0.0.0.0:53 # 开启 DNS 服务器监听
  ipv6: false # false 将返回 AAAA 的空结果
  respect-rules: true # 遵循规则
  enhanced-mode: fake-ip # 使用fake-ip模式
  behavior: strict
  fake-ip-range: 198.18.0.1/16 # Fake IP 池设置
  fake-ip-filter-mode: blacklist

  # 用于解析 nameserver，fallback 以及其他 DNS 服务器配置的 DNS 服务器域名
  default-nameserver:
    - tls://223.5.5.5
    - tls://223.6.6.6
  
  # 配置不使用 fake-ip 的域名
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - '*.arpa'
    - time.*.com
    - ntp.*.com
    - +.xiaomi.com
    - localhost.ptlogin2.qq.com
    - geosite:private
    - geosite:cn

  # 配置 DNS 服务器
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  
  # 配置 DNS 策略
  nameserver-policy:
    "geosite:cn,private,apple":
      - https://doh.pub/dns-query
      - https://dns.alidns.com/dns-query
    "geosite:geolocation-!cn":
      - https://dns.cloudflare.com/dns-query
      - https://dns.google/dns-query

  # 当配置 fallback 时，会查询 nameserver 中返回的 IP 是否为 CN，非必要配置
  # 当不是 CN，则使用 fallback 中的 DNS 查询结果
  fallback:
    - https://dns.cloudflare.com/dns-query
    - https://dns.google/dns-query
  fallback-filter:
    geoip: true # 配置是否使用 geoip
    geoip-code: CN # 当 nameserver 域名的 IP 查询 geoip 库为 CN 时，不使用 fallback 中的 DNS 查询结果
    ipcidr:
      - ::/128
      - ::1/128
      - 2001::/32
      - 0.0.0.0/8
      - 10.0.0.0/8
      - 100.64.0.0/10
      - 127.0.0.0/8
      - 169.254.0.0/16
      - 172.16.0.0/12
      - 192.0.0.0/24
      - 192.0.2.0/24
      - 192.88.99.0/24
      - 192.168.0.0/16
      - 198.18.0.0/15
      - 198.51.100.0/24
      - 203.0.113.0/24
      - 224.0.0.0/4
      - 240.0.0.0/4
      - 255.255.255.255/32
  
  proxy-server-nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query

# 嗅探配置
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"
    - "+.push.apple.com"

# 策略组引用
Pro: &a1 {type: http, interval: 28800, health-check: {enable: true, url: http://www.gstatic.com/generate_204, interval: 1800}, override: {skip-cert-verify: true, udp: true}}
manual: &a2 {type: select, use: [Subscribe]}
classical: &a3 {type: http, behavior: classical, interval: 28800}

proxy-providers:
  Subscribe:
    <<: *a1
    url: $suburl
    path: ./SelfHost.yaml

proxy-groups:
  # 默认
  - {name: 默认, <<: *a2, icon: https://gitee.com/hoofei/clash/raw/main/icons/Manual.png }
  # 分流
  - {name: AI, type: select, proxies: [默认], icon: https://gitee.com/hoofei/clash/raw/main/icons/AI.png }
  - {name: TikTok, type: select, proxies: [默认], icon: https://gitee.com/hoofei/clash/raw/main/icons/TikTok.png }
  - {name: Netflix, type: select, proxies: [默认], icon: https://gitee.com/hoofei/clash/raw/main/icons/Netflix.png }

rule-providers:
  AI: {<<: *a3, url: https://gitee.com/hoofei/clash/raw/main/rules/AI.yaml, path: ./ruleset/AI.yaml}
  TikTok: {<<: *a3, url: https://gitee.com/hoofei/clash/raw/main/rules/TikTok.yaml, path: ./ruleset/TikTok.yaml}
  Netflix: {<<: *a3, url: https://gitee.com/hoofei/clash/raw/main/rules/Netflix.yaml, path: ./ruleset/Netflix.yaml}
  WeChat: {<<: *a3, url: https://gitee.com/hoofei/clash/raw/main/rules/WeChat.yaml, path: ./ruleset/WeChat.yaml}
  Steam: {<<: *a3, url: https://gitee.com/hoofei/clash/raw/main/rules/Steam.yaml, path: ./ruleset/Steam.yaml}
  
rules:
# 分流
  - RULE-SET,AI,AI
  - RULE-SET,TikTok,TikTok
  - RULE-SET,Netflix,Netflix
  - RULE-SET,WeChat,DIRECT
  - RULE-SET,Steam,DIRECT
  - DOMAIN-SUFFIX,doh.pub,DIRECT
  - DOMAIN-SUFFIX,alidns.com,DIRECT
  - DOMAIN-SUFFIX,cloudflare-dns.com,默认
  - DOMAIN-SUFFIX,dns.google,默认
  - DOMAIN,1.1.1.1,默认
  - DOMAIN,8.8.8.8,默认
  - DOMAIN,9.9.9.9,默认
  - GEOIP,CN,DIRECT,no-resolve
  - MATCH,默认